//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragatiAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int PaymentDetailID { get; set; }
        public int PaymentMasterID { get; set; }
        public int InvoiceID { get; set; }
        public int ReceiveAmount { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public int Discount { get; set; }
        public int BalAmount { get; set; }
        public bool Isdeleted { get; set; }
    }
}
